# Generated by Django 3.2.20 on 2023-09-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_sensormeasurement_sensorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensormeasurement',
            old_name='sensorID',
            new_name='measurements',
        ),
    ]
